services:
  - type: web
    name: dh-shop
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.9
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com

databases:
  - name: dh-shop-db
    databaseName: ecommerce_db
    user: ecommerce_user
    plan: free